### PR TITLE
Fix some erros. Idk why the hell I did it the way I did. 🚀

### PR DESCRIPTION
**Pull request by OliKue**

### CODE REVIEW

**Comment by abteilung6** [comment]
@steven-mi

**Comment by steven-mi** [comment]
@abteilung6

**Comment by abteilung6** [comment]
@steven-mi please can u review ASAP. ThAnKs

**Comment by steven-mi** [comment]
@abteilung6 I don´t know how to aprove

**Comment by abteilung6** [comment]
The fiver guy who devloped this project does not reply anymore. So i can not review these critical Bugfixes.. 
@steven-mi

**Comment by steven-mi** [comment]
@abteilung6 DOGE TO MOON🚀🚀🚀🚀🚀

**Pull request merged**
